# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(411, 526)
        font = QtGui.QFont()
        font.setPointSize(8)
        Registration.setFont(font)
        self.LoginLabel = QtWidgets.QLabel(Registration)
        self.LoginLabel.setGeometry(QtCore.QRect(9, 78, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setObjectName("LoginLabel")
        self.PasswordLabel = QtWidgets.QLabel(Registration)
        self.PasswordLabel.setGeometry(QtCore.QRect(9, 134, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.RepeatPasswordLabel = QtWidgets.QLabel(Registration)
        self.RepeatPasswordLabel.setGeometry(QtCore.QRect(9, 190, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RepeatPasswordLabel.setFont(font)
        self.RepeatPasswordLabel.setObjectName("RepeatPasswordLabel")
        self.PhoneLabel = QtWidgets.QLabel(Registration)
        self.PhoneLabel.setGeometry(QtCore.QRect(9, 246, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PhoneLabel.setFont(font)
        self.PhoneLabel.setObjectName("PhoneLabel")
        self.NameLabel = QtWidgets.QLabel(Registration)
        self.NameLabel.setGeometry(QtCore.QRect(9, 302, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.LastNameLabel = QtWidgets.QLabel(Registration)
        self.LastNameLabel.setGeometry(QtCore.QRect(9, 358, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LastNameLabel.setFont(font)
        self.LastNameLabel.setObjectName("LastNameLabel")
        self.Email = QtWidgets.QLabel(Registration)
        self.Email.setGeometry(QtCore.QRect(9, 414, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Email.setFont(font)
        self.Email.setObjectName("Email")
        self.LoginLineEdit = QtWidgets.QLineEdit(Registration)
        self.LoginLineEdit.setGeometry(QtCore.QRect(130, 78, 221, 20))
        self.LoginLineEdit.setObjectName("LoginLineEdit")
        self.PasswordLineEdit = QtWidgets.QLineEdit(Registration)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(130, 134, 221, 20))
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.RepeatPasswordLineEdit = QtWidgets.QLineEdit(Registration)
        self.RepeatPasswordLineEdit.setGeometry(QtCore.QRect(130, 190, 221, 20))
        self.RepeatPasswordLineEdit.setObjectName("RepeatPasswordLineEdit")
        self.PhoneNumberLineEdit = QtWidgets.QLineEdit(Registration)
        self.PhoneNumberLineEdit.setGeometry(QtCore.QRect(130, 246, 221, 20))
        self.PhoneNumberLineEdit.setObjectName("PhoneNumberLineEdit")
        self.NameLineEdit = QtWidgets.QLineEdit(Registration)
        self.NameLineEdit.setGeometry(QtCore.QRect(130, 302, 221, 20))
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.LastNameLineEdit = QtWidgets.QLineEdit(Registration)
        self.LastNameLineEdit.setGeometry(QtCore.QRect(130, 358, 221, 20))
        self.LastNameLineEdit.setObjectName("LastNameLineEdit")
        self.EmailLineEdit = QtWidgets.QLineEdit(Registration)
        self.EmailLineEdit.setGeometry(QtCore.QRect(130, 414, 221, 20))
        self.EmailLineEdit.setObjectName("EmailLineEdit")
        self.BackPushButton = QtWidgets.QPushButton(Registration)
        self.BackPushButton.setGeometry(QtCore.QRect(60, 470, 111, 25))
        self.BackPushButton.setObjectName("BackPushButton")
        self.RegisterPushButton = QtWidgets.QPushButton(Registration)
        self.RegisterPushButton.setGeometry(QtCore.QRect(240, 470, 111, 25))
        self.RegisterPushButton.setObjectName("RegisterPushButton")
        self.InfoLabel = QtWidgets.QLabel(Registration)
        self.InfoLabel.setGeometry(QtCore.QRect(10, 20, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.InfoLabel.setFont(font)
        self.InfoLabel.setObjectName("InfoLabel")
        self.LoginError = QtWidgets.QLabel(Registration)
        self.LoginError.setGeometry(QtCore.QRect(130, 100, 221, 16))
        self.LoginError.setText("")
        self.LoginError.setObjectName("LoginError")
        self.PasswordError = QtWidgets.QLabel(Registration)
        self.PasswordError.setGeometry(QtCore.QRect(130, 155, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PasswordError.setFont(font)
        self.PasswordError.setText("")
        self.PasswordError.setObjectName("PasswordError")
        self.RepeatPassworError = QtWidgets.QLabel(Registration)
        self.RepeatPassworError.setGeometry(QtCore.QRect(130, 210, 221, 16))
        self.RepeatPassworError.setText("")
        self.RepeatPassworError.setObjectName("RepeatPassworError")
        self.PhoneNumberError = QtWidgets.QLabel(Registration)
        self.PhoneNumberError.setGeometry(QtCore.QRect(130, 270, 221, 16))
        self.PhoneNumberError.setText("")
        self.PhoneNumberError.setObjectName("PhoneNumberError")
        self.NameError = QtWidgets.QLabel(Registration)
        self.NameError.setGeometry(QtCore.QRect(130, 320, 221, 16))
        self.NameError.setText("")
        self.NameError.setObjectName("NameError")
        self.LastNameError = QtWidgets.QLabel(Registration)
        self.LastNameError.setGeometry(QtCore.QRect(130, 380, 221, 16))
        self.LastNameError.setText("")
        self.LastNameError.setObjectName("LastNameError")
        self.EmailError = QtWidgets.QLabel(Registration)
        self.EmailError.setGeometry(QtCore.QRect(130, 440, 221, 16))
        self.EmailError.setText("")
        self.EmailError.setObjectName("EmailError")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Registration"))
        self.LoginLabel.setText(_translate("Registration", "Логін"))
        self.PasswordLabel.setText(_translate("Registration", "Пароль"))
        self.RepeatPasswordLabel.setText(_translate("Registration", "Повторіть пароль"))
        self.PhoneLabel.setText(_translate("Registration", "Номер телефону"))
        self.NameLabel.setText(_translate("Registration", "Ім\'я"))
        self.LastNameLabel.setText(_translate("Registration", "Прізвище"))
        self.Email.setText(_translate("Registration", "Емейл"))
        self.BackPushButton.setText(_translate("Registration", "Назад"))
        self.RegisterPushButton.setText(_translate("Registration", "Зареєструватись"))
        self.InfoLabel.setText(_translate("Registration", "Для реєстрації в сервісі MoneySaver заповніть всі поля"))

