# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(411, 526)
        font = QtGui.QFont()
        font.setPointSize(8)
        Registration.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Registration.setWindowIcon(icon)
        self.loginLabel = QtWidgets.QLabel(Registration)
        self.loginLabel.setGeometry(QtCore.QRect(9, 78, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loginLabel.setFont(font)
        self.loginLabel.setObjectName("loginLabel")
        self.passwordLabel = QtWidgets.QLabel(Registration)
        self.passwordLabel.setGeometry(QtCore.QRect(9, 134, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.repeatPasswordLabel = QtWidgets.QLabel(Registration)
        self.repeatPasswordLabel.setGeometry(QtCore.QRect(9, 190, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.repeatPasswordLabel.setFont(font)
        self.repeatPasswordLabel.setObjectName("repeatPasswordLabel")
        self.phoneLabel = QtWidgets.QLabel(Registration)
        self.phoneLabel.setGeometry(QtCore.QRect(9, 246, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setObjectName("phoneLabel")
        self.nameLabel = QtWidgets.QLabel(Registration)
        self.nameLabel.setGeometry(QtCore.QRect(9, 302, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.lastNameLabel = QtWidgets.QLabel(Registration)
        self.lastNameLabel.setGeometry(QtCore.QRect(9, 358, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.email = QtWidgets.QLabel(Registration)
        self.email.setGeometry(QtCore.QRect(9, 414, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.loginLineEdit = QtWidgets.QLineEdit(Registration)
        self.loginLineEdit.setGeometry(QtCore.QRect(130, 78, 221, 20))
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.loginLineEdit.setMaxLength(25)
        self.passwordLineEdit = QtWidgets.QLineEdit(Registration)
        self.passwordLineEdit.setGeometry(QtCore.QRect(130, 134, 221, 20))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordLineEdit.setEchoMode(2)
        self.passwordLineEdit.setMaxLength(25)
        self.repeatPasswordLineEdit = QtWidgets.QLineEdit(Registration)
        self.repeatPasswordLineEdit.setGeometry(QtCore.QRect(130, 190, 221, 20))
        self.repeatPasswordLineEdit.setObjectName("repeatPasswordLineEdit")
        self.repeatPasswordLineEdit.setMaxLength(25)
        self.repeatPasswordLineEdit.setEchoMode(2)
        self.phoneNumberLineEdit = QtWidgets.QLineEdit(Registration)
        self.phoneNumberLineEdit.setGeometry(QtCore.QRect(130, 246, 221, 20))
        self.phoneNumberLineEdit.setObjectName("phoneNumberLineEdit")
        self.phoneNumberLineEdit.setInputMask("+38(999)9999999")
        self.nameLineEdit = QtWidgets.QLineEdit(Registration)
        self.nameLineEdit.setGeometry(QtCore.QRect(130, 302, 221, 20))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameLineEdit.setInputMask("AAaaaaaaaaaaaaaaaaaaaaaaaa")
        self.lastNameLineEdit = QtWidgets.QLineEdit(Registration)
        self.lastNameLineEdit.setGeometry(QtCore.QRect(130, 358, 221, 20))
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.lastNameLineEdit.setInputMask("AAaaaaaaaaaaaaaaaaaaaaaaaa")
        self.emailLineEdit = QtWidgets.QLineEdit(Registration)
        self.emailLineEdit.setGeometry(QtCore.QRect(130, 414, 221, 20))
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.emailLineEdit.setMaxLength(25)
        self.BackPushButton = QtWidgets.QPushButton(Registration)
        self.BackPushButton.setGeometry(QtCore.QRect(60, 470, 111, 25))
        self.BackPushButton.setObjectName("BackPushButton")
        self.RegisterPushButton = QtWidgets.QPushButton(Registration)
        self.RegisterPushButton.setGeometry(QtCore.QRect(240, 470, 111, 25))
        self.RegisterPushButton.setObjectName("RegisterPushButton")
        self.InfoLabel = QtWidgets.QLabel(Registration)
        self.InfoLabel.setGeometry(QtCore.QRect(10, 20, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.InfoLabel.setFont(font)
        self.InfoLabel.setObjectName("InfoLabel")
        self.loginError = QtWidgets.QLabel(Registration)
        self.loginError.setGeometry(QtCore.QRect(130, 100, 221, 16))
        self.loginError.setText("")
        self.loginError.setObjectName("loginError")
        self.passwordError = QtWidgets.QLabel(Registration)
        self.passwordError.setGeometry(QtCore.QRect(130, 155, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.passwordError.setFont(font)
        self.passwordError.setText("")
        self.passwordError.setObjectName("passwordError")
        self.repeatPassworError = QtWidgets.QLabel(Registration)
        self.repeatPassworError.setGeometry(QtCore.QRect(130, 210, 221, 16))
        self.repeatPassworError.setText("")
        self.repeatPassworError.setObjectName("repeatPassworError")
        self.phoneNumberError = QtWidgets.QLabel(Registration)
        self.phoneNumberError.setGeometry(QtCore.QRect(130, 270, 221, 16))
        self.phoneNumberError.setText("")
        self.phoneNumberError.setObjectName("phoneNumberError")
        self.nameError = QtWidgets.QLabel(Registration)
        self.nameError.setGeometry(QtCore.QRect(130, 320, 221, 16))
        self.nameError.setText("")
        self.nameError.setObjectName("nameError")
        self.lastNameError = QtWidgets.QLabel(Registration)
        self.lastNameError.setGeometry(QtCore.QRect(130, 380, 221, 16))
        self.lastNameError.setText("")
        self.lastNameError.setObjectName("lastNameError")
        self.EmailError = QtWidgets.QLabel(Registration)
        self.EmailError.setGeometry(QtCore.QRect(130, 436, 221, 16))
        self.EmailError.setText("")
        self.EmailError.setObjectName("EmailError")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Registration"))
        self.loginLabel.setText(_translate("Registration", "Логін"))
        self.passwordLabel.setText(_translate("Registration", "Пароль"))
        self.repeatPasswordLabel.setText(_translate("Registration", "Повторіть пароль"))
        self.phoneLabel.setText(_translate("Registration", "Номер телефону"))
        self.nameLabel.setText(_translate("Registration", "Ім\'я"))
        self.lastNameLabel.setText(_translate("Registration", "Прізвище"))
        self.email.setText(_translate("Registration", "Пошта"))
        self.BackPushButton.setText(_translate("Registration", "Назад"))
        self.RegisterPushButton.setText(_translate("Registration", "Зареєструватись"))
        self.InfoLabel.setText(_translate("Registration", "Для реєстрації в сервісі MoneySaver заповніть всі поля"))

