# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_info.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserInfo(object):
    def setupUi(self, UserInfo):
        UserInfo.setObjectName("UserInfo")
        UserInfo.resize(855, 579)
        UserInfo.setMaximumSize(QtCore.QSize(855, 579))
        UserInfo.setSizeIncrement(QtCore.QSize(855, 579))
        self.info_label = QtWidgets.QLabel(UserInfo)
        self.info_label.setGeometry(QtCore.QRect(10, 20, 701, 16))
        self.info_label.setObjectName("info_label")
        self.month_comboBox = QtWidgets.QComboBox(UserInfo)
        self.month_comboBox.setGeometry(QtCore.QRect(380, 20, 120, 22))
        self.month_comboBox.setObjectName("month_comboBox")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.year_comboBox = QtWidgets.QComboBox(UserInfo)
        self.year_comboBox.setGeometry(QtCore.QRect(530, 20, 120, 22))
        self.year_comboBox.setObjectName("year_comboBox")
        self.year_comboBox.addItem("")
        self.year_comboBox.addItem("")
        self.year_comboBox.addItem("")
        self.confirm_button = QtWidgets.QPushButton(UserInfo)
        self.confirm_button.setGeometry(QtCore.QRect(700, 20, 120, 23))
        self.confirm_button.setObjectName("confirm_button")
        self.costs_tableWidget = QtWidgets.QTableWidget(UserInfo)
        self.costs_tableWidget.setGeometry(QtCore.QRect(10, 60, 831, 461))
        self.costs_tableWidget.setObjectName("costs_tableWidget")
        self.costs_tableWidget.setColumnCount(4)
        self.costs_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.costs_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.costs_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.costs_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.costs_tableWidget.setHorizontalHeaderItem(3, item)
        self.costs_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.costs_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.back_button = QtWidgets.QPushButton(UserInfo)
        self.back_button.setGeometry(QtCore.QRect(10, 540, 171, 23))
        self.back_button.setObjectName("back_button")
        self.add_new_cost_button = QtWidgets.QPushButton(UserInfo)
        self.add_new_cost_button.setGeometry(QtCore.QRect(450, 540, 171, 23))
        self.add_new_cost_button.setObjectName("add_new_cost_button")
        self.edit_plane_button = QtWidgets.QPushButton(UserInfo)
        self.edit_plane_button.setGeometry(QtCore.QRect(670, 540, 171, 23))
        self.edit_plane_button.setObjectName("edit_plane_button")
        self.refresh_data_button = QtWidgets.QPushButton(UserInfo)
        self.refresh_data_button.setGeometry(QtCore.QRect(240, 540, 171, 23))
        self.refresh_data_button.setObjectName("refresh_data_button")

        self.retranslateUi(UserInfo)
        QtCore.QMetaObject.connectSlotsByName(UserInfo)

    def retranslateUi(self, UserInfo):
        _translate = QtCore.QCoreApplication.translate
        UserInfo.setWindowTitle(_translate("UserInfo", "Моя історія"))
        self.info_label.setText(_translate("UserInfo", "Вкажіть проміжок часу, за який хочете переглянути історію витрат"))
        self.month_comboBox.setItemText(0, _translate("UserInfo", "Січень"))
        self.month_comboBox.setItemText(1, _translate("UserInfo", "Лютий"))
        self.month_comboBox.setItemText(2, _translate("UserInfo", "Березень"))
        self.month_comboBox.setItemText(3, _translate("UserInfo", "Квітень"))
        self.month_comboBox.setItemText(4, _translate("UserInfo", "Травень"))
        self.month_comboBox.setItemText(5, _translate("UserInfo", "Червень"))
        self.month_comboBox.setItemText(6, _translate("UserInfo", "Липень"))
        self.month_comboBox.setItemText(7, _translate("UserInfo", "Серпень"))
        self.month_comboBox.setItemText(8, _translate("UserInfo", "Вересень"))
        self.month_comboBox.setItemText(9, _translate("UserInfo", "Жовтень"))
        self.month_comboBox.setItemText(10, _translate("UserInfo", "Листопад"))
        self.month_comboBox.setItemText(11, _translate("UserInfo", "Грудень"))
        self.year_comboBox.setItemText(0, _translate("UserInfo", "2014 рік"))
        self.year_comboBox.setItemText(1, _translate("UserInfo", "2015 рік"))
        self.year_comboBox.setItemText(2, _translate("UserInfo", "2016 рік"))
        self.confirm_button.setText(_translate("UserInfo", "Підтвердити"))
        item = self.costs_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UserInfo", "Категорія"))
        item = self.costs_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UserInfo", "Сума"))
        item = self.costs_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("UserInfo", "Дата"))
        item = self.costs_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("UserInfo", "Коментар"))
        self.back_button.setText(_translate("UserInfo", "Назад"))
        self.add_new_cost_button.setText(_translate("UserInfo", "Додати нову витрату"))
        self.edit_plane_button.setText(_translate("UserInfo", "Редагувати план витрат"))
        self.refresh_data_button.setText(_translate("UserInfo", "Оновити дані"))

